name: Build using Cloud Build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Review-Endpoint/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Review-Endpoint/**'

env:
  PROJECT_ID: red-bruin-349004
  SERVICE_NAME: review

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        # If your project is not in the root, please change it to the directory
        # where there's a Dockerfile.
        # You can fill it like this.
        # working-directory: "./some-folder-with-dockerfile"
        working-directory: "./Review-Endpoint"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Authentication process
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" .
